C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook>npm run deploy
> physical-ai-humanoid-robotics-textbook@0.1.0 deploy
> docusaurus deploy

[WARNING] The `siteConfig.onBrokenMarkdownLinks` config option is deprecated and will be removed in Docusaurus v4.
Please migrate and move this option to `siteConfig.markdown.hooks.onBrokenMarkdownLinks` instead.
[INFO] Deploy command invoked...
[INFO] `git --version` code: 0
[INFO] organizationName: munizazubair
[INFO] projectName: Physical-AI-Humanoid-Robotics-Textbook
[INFO] deploymentBranch: gh-pages
[INFO] Remote repo URL: git@github.com:munizazubair/Physical-AI-Humanoid-Robotics-Textbook.git
[INFO] `git rev-parse HEAD` code: 0
[WARNING] The `siteConfig.onBrokenMarkdownLinks` config option is deprecated and will be removed in Docusaurus v4.
Please migrate and move this option to `siteConfig.markdown.hooks.onBrokenMarkdownLinks` instead.
[INFO] [en] Creating an optimized production build...
[WARNING] The `siteConfig.onBrokenMarkdownLinks` config option is deprecated and will be removed in Docusaurus v4.
Please migrate and move this option to `siteConfig.markdown.hooks.onBrokenMarkdownLinks` instead.

√ Client
  Compiled successfully in 2.31m

√ Server

* Client █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

√ Server

[WARNING] Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:
- Broken link on source page path = /Physical-AI-Humanoid-Robotics-Textbook/:
   -> linking to /Physical-AI-Humanoid-Robotics-Textbook/docs/intro
   -> linking to /Physical-AI-Humanoid-Robotics-Textbook/docs/module-1-ros2/03-intro-ros2
   -> linking to /Physical-AI-Humanoid-Robotics-Textbook/docs/module-2-digital-twin/07-intro-digital-twins
   -> linking to /Physical-AI-Humanoid-Robotics-Textbook/docs/module-3-nvidia-isaac/11-intro-isaac
   -> linking to /Physical-AI-Humanoid-Robotics-Textbook/docs/module-4-vla/15-intro-vla
   -> linking to /Physical-AI-Humanoid-Robotics-Textbook/docs/foundation/01-intro-physical-ai

[SUCCESS] Generated static files in "build".
[INFO] Use `npm run serve` command to test your build locally.
[ERROR] Deployment of the build output failed.

[ERROR] Error: Error while executing command `git clone --depth 1 --branch gh-pages git@github.com:munizazubair/Physical-AI-Humanoid-Robotics-Textbook.git C:\Users\SIBGHAT\AppData\Local\Temp\Physical-AI-Humanoid-Robotics-Textbook-gh-pages3RxFpo`
In CWD `C:\Users\SIBGHAT\AppData\Local\Temp\Physical-AI-Humanoid-Robotics-Textbook-gh-pages3RxFpo`
    at exec (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\@docusaurus\core\lib\commands\deploy.js:47:15)
    at runDeploy (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\@docusaurus\core\lib\commands\deploy.js:170:13)
    ... 3 lines matching cause stack trace ...
    at async file:///C:/Users/SIBGHAT/OneDrive/Desktop/speckitplus-hackathon/Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01/Physical-AI-Humanoid-Robotics-Textbook/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error: Command failed with exit code 128: git clone --depth 1 --branch
gh-pages git@github.com:munizazubair/Physical-AI-Humanoid-Robotics-Textbook.git C:\Users\SIBGHAT\AppData\Local\Temp\Physical-AI-Humanoid-Robotics-Textbook-gh-pages3RxFpo
  Cloning into 'C:\Users\SIBGHAT\AppData\Local\Temp\Physical-AI-Humanoid-Robotics-Textbook-gh-pages3RxFpo'...
  ERROR: Repository not found.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
      at makeError (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\execa\lib\error.js:60:11)
      at module.exports.sync (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\execa\index.js:194:17)
      at module.exports.commandSync (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\execa\index.js:235:15)
      at exec (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\@docusaurus\core\lib\commands\deploy.js:34:40)
      at runDeploy (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\@docusaurus\core\lib\commands\deploy.js:170:13)
      at async Command.deploy (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\@docusaurus\core\lib\commands\deploy.js:229:13)
      at async Promise.all (index 0)
      at async runCLI (C:\Users\SIBGHAT\OneDrive\Desktop\speckitplus-hackathon\Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01\Physical-AI-Humanoid-Robotics-Textbook\node_modules\@docusaurus\core\lib\commands\cli.js:56:5)
      at async file:///C:/Users/SIBGHAT/OneDrive/Desktop/speckitplus-hackathon/Physical-AI-Humanoid-Robotics-Textbook--Hackathon-01/Physical-AI-Humanoid-Robotics-Textbook/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
    shortMessage: 'Command failed with exit code 128: git clone --depth 1 --branch gh-pages git@github.com:munizazubair/Physical-AI-Humanoid-Robotics-Textbook.git C:\\Users\\SIBGHAT\\AppData\\Local\\Temp\\Physical-AI-Humanoid-Robotics-Textbook-gh-pages3RxFpo',
    command: 'git clone --depth 1 --branch gh-pages git@github.com:munizazubair/Physical-AI-Humanoid-Robotics-Textbook.git C:\\Users\\SIBGHAT\\AppData\\Local\\Temp\\Physical-AI-Humanoid-Robotics-Textbook-gh-pages3RxFpo',
    escapedCommand: 'git clone --depth 1 --branch gh-pages "git@github.com:munizazubair/Physical-AI-Humanoid-Robotics-Textbook.git" "C:\\Users\\SIBGHAT\\AppData\\Local\\Temp\\Physical-AI-Humanoid-Robotics-Textbook-gh-pages3RxFpo"',
    exitCode: 128,
    signal: undefined,
    signalDescription: undefined,
    stdout: '',
      'ERROR: Repository not found.\n' +                                  cal-AI-H
      'fatal: Could not read from remote repository.\n' +
      '\n' +
      'Please make sure you have the correct access rights\n' +
      'and the repository exists.',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
}
[INFO] Docusaurus version: 3.9.2
Node version: v22.13.1